import turtle as t
from Grid_Building import grid_template
from Mazes.maze_generator import Generate
from Mazes.maze_solver import Solve


"""BUILDING A GRID"""

"""Creates a grid object:
    parameters (required):
        - Number of columns, number of rows
    parameters (optional)
        - cell_dim - default is 20; sets the dimensions of each cell.
        - border - default is 40; sets the border of the grid
        - bg_color - default is lightgreen, sets the background color of the gris 
        - hide_grid - default is False, hides the grid 
        - line_color default is black; the color of the lines in the grid
        - line_thickness_vert - default is 1; change the thickness of vertical lines in grid
        - line_thickness_hor - default is 1; change the thickness of horizontal lines in the grid 
    """
grid = grid_template.grid(40, 40,
                          cell_dim=10,
                          border=30,
                          bg_color='cyan',
                          hide_grid=False,
                          line_color='black',
                          line_thickness_vert=1,
                          line_thickness_hor=1)  # create a grid object
# Build the grid
grid.build_grid()


"""Grid Methods available
    - self.get_neighbors(row, column) - returns a list of tuples with the following; 
        (row of neighbor cell, column of neighbor cell, direction of neighbor cell relative to the cell passed in)
    
    - self.get_cell_boundaries_single (row, columns) - Returns a list representing the left, right, bottom, and top absolute dimensions of the cell
      relative to the turtle coordinate system. NOTE! The top-left cell is (1,1), not (0,0).
      Passing in a cell outside the bounds of the grid returns NONE 
      
    - self. grid_data_centers() - returns a 2d-list of tuples representing the center point of each cell in the grid with the following information:
        (x-coordinate of center, y-coordinate of center, cell number (starting with 1 and moving horizontally))
    
    -  self. get_connections_all() - returns a list of tuple pairs representing all possible combination of cells that are neighbors.
        NOTE! THis is 0 indexed, so top left cell is (0,0)
    """
get_neighbors = grid.get_neighbors(0,0)
# print(get_neighbors)

get_cell_boundaries_single = grid.get_cell_boundaries_single
# print(get_cell_boundaries_single(1,1))

grid_data_centers = grid.grid_data_centers
# print(grid_data_centers())

get_connections_all = grid.get_connections_all
# print(get_connections_all())

""" 
                --- GENERATING A MAZE ---

    A maze can be generated using the grid object created above. 
    The Generate class from the maze_generator.py contains all the methods.
    

    Create an object for generating the maze by passing in a grid object on which the maze will be created.
    the grid must be defined beforehand as demonstrated above."""

maze_generator = Generate(grid)

"""Mazes can be generated using depth-first-search (DFS) algorithm or Kruskals algorithm.
    HOWEVER, using both will lead to undesirable outcomes

    THe algorithms are accessible in the Algorithms folder and imported by thr maze_generator module"""

""" Generate a maze using a depth-first-search (DFS) algorithm
    Pass in the (row, column) where the algorithm starts"""
maze_generator.generate_maze_DFS(0, 0)


""" Use Kruskals algorithm to generate the maze
    Due to the algorithm, generation starts at a random location so no parameters are needed"""
# maze_generator.generate_maze_kruskals()

"""The self.get_accessible_neighbors(row, column) method returns all neighbors that are accessible relative to the cell passed in.
    In other words, it returns neighbors where the line (wall) connecting them is removed relative to the passed in cell"""
accessible_neighbors = maze_generator.get_accessible_neighbors(0,0)
print(accessible_neighbors)

""" The self.get_accessible_neighbors() method returns a 2D list representing walls (with a 1) and passages (with a 0) """
walls_and_passages = maze_generator.get_maze_data()
# print(walls_and_passages)

"""Note - other methods that help with the data of the grid can be accesses, see the maze_generator.py file for more."""


"""
#         -- MAZE SOLVER --
#     Solves the maze generated by the maze generator object shown above using the same grid as described earlier.
#     The class Solve inside of maze_solver.py contains the methods needed.
#
#     The maze generator object is passed into the class, referencing the maze to solve.
# """
maze_solution = Solve(maze_generator)

"""
    Two algorithms can be used to solve. Both can be used on the same maze at once.

    1) Depth-first search (DFS)
    2) Breadth-first search (BFS)
"""

maze_solution.solve_DFS()
maze_solution.solve_BFS()

# Display everything, keeps screen from closing
t.done()